- name: Installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - mysql
        - git
        - zip

