- name: packages installing
  hosts: local
  connection: local
  tasks:
  - name: installing packages
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - htop
    - net-tools
    - tree
    - python3
    - python3-pip
