- name: Installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Installing or removing packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'git', state: 'present' }
        - { name: 'mysql', state: 'present' }
        - { name: 'gcc', state: 'absent' }
        - { name: 'zip', state: 'present' }

