- name: "DevOps Information"
  hosts: localhost
  connection: local
  vars:
    course_name: "DevOps with aws"
    duration: 120hrs
    topics:
      - linux
      - ansible
      - shell
      - aws
    live: true  # boolean
    tools:      # map
      ci_cd: jenkins
      containerization: docker
      orchestration: kubernetes

  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "Hello All I am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, it is {{ live }}, tools covered are: {{ tools }}"

