- name: variables from files
  hosts: web
  connection: local
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} and the duration is {{ DURATION }} and the tutor is {{ TUTOR }}"
